// resources/js/Layouts/AppLayout.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import { Link, usePage, router } from '@inertiajs/vue3';
import {
    LayoutDashboard,
    FileSpreadsheet,
    Store,
    Layers,
    Cpu,
    Play,
    Loader2,
    Clock,
    Sparkles,
    CheckCircle2,
    AlertCircle,
    Menu,
    X,
    TrendingUp
} from 'lucide-vue-next';
import { Toaster, toast } from 'vue-sonner';

defineProps<{
    title?: string;
}>();

const page = usePage();
const isGenerating = ref(false);
const mobileMenuOpen = ref(false);

const navItems = [
    { name: 'Dashboard', href: '/', icon: LayoutDashboard, current: (url: string) => url === '/' },
    { name: 'TikTok Breakdown', href: '/tiktok', icon: TrendingUp, current: (url: string) => url.startsWith('/tiktok'), highlight: true },
    { name: 'Reports', href: '/reports', icon: FileSpreadsheet, current: (url: string) => url.startsWith('/reports') },
    { name: 'Shops', href: '/shops', icon: Store, current: (url: string) => url.startsWith('/shops') },
    { name: 'Platforms', href: '/platforms', icon: Layers, current: (url: string) => url.startsWith('/platforms') },
    { name: 'Automation', href: '/automation', icon: Cpu, current: (url: string) => url.startsWith('/automation') },
];

// Live Philippine Standard Time clock
const phtTime = ref('');
let timer: ReturnType<typeof setInterval> | null = null;

function updateClock() {
    try {
        const now = new Date();
        phtTime.value = new Intl.DateTimeFormat('en-US', {
            timeZone: 'Asia/Manila',
            hour: 'numeric',
            minute: '2-digit',
            second: '2-digit',
            hour12: true
        }).format(now);
    } catch {
        phtTime.value = 'PHT';
    }
}

onMounted(() => {
    updateClock();
    timer = setInterval(updateClock, 1000);
});

onUnmounted(() => {
    if (timer) clearInterval(timer);
});

function triggerReportGeneration() {
    if (isGenerating.value) return;
    isGenerating.value = true;
    const toastId = toast.loading('Generating hourly snapshot report...');

    router.post('/reports/generate', {}, {
        onSuccess: () => {
            toast.success('Hourly snapshot generated successfully!', { id: toastId });
        },
        onError: () => {
            toast.error('Failed to generate report. Check automation logs.', { id: toastId });
        },
        onFinish: () => {
            isGenerating.value = false;
        }
    });
}
</script>

<template>
    <div class="min-h-screen bg-slate-50 flex flex-col text-slate-900 pb-16 md:pb-0">
        <!-- Toast Notification Container -->
        <Toaster position="top-right" richColors :expand="false" />

        <!-- Top Prototype Notice Banner -->
        <div class="bg-amber-500/10 border-b border-amber-500/20 text-amber-900 px-4 py-2 text-xs font-medium">
            <div class="flex items-center justify-between max-w-7xl mx-auto w-full gap-3">
                <div class="flex items-center gap-2">
                    <span class="inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider bg-amber-200/80 text-amber-950 border border-amber-300">
                        <Sparkles class="w-3 h-3" :stroke-width="2" />
                        Prototype
                    </span>
                    <span class="text-xs">
                        <strong>DEMO DATA MODE:</strong> Figures, shops, and metrics displayed are simulated for multi-platform architectural demonstration.
                    </span>
                </div>
                <div class="hidden sm:flex items-center gap-1.5 text-[11px] text-amber-800/80 bg-amber-100/60 px-2.5 py-0.5 rounded-full border border-amber-200">
                    <Clock class="w-3 h-3 text-amber-700" :stroke-width="2" />
                    <span>Philippine Standard Time (PHT, UTC+8)</span>
                </div>
            </div>
        </div>

        <!-- Main Navigation Header with Glassmorphism -->
        <header class="bg-white/90 backdrop-blur-md border-b border-slate-200/80 sticky top-0 z-30 shadow-2xs transition-all">
            <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div class="flex items-center justify-between h-16">
                    <!-- Left: Brand + Live Time -->
                    <div class="flex items-center gap-4">
                        <Link href="/" class="flex items-center gap-3 group">
                            <div class="w-10 h-10 rounded-xl bg-indigo-600 text-white flex items-center justify-center font-bold text-lg shadow-sm shadow-indigo-600/20 group-hover:bg-indigo-700 transition duration-200 group-hover:scale-105">
                                <svg class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" />
                                </svg>
                            </div>
                            <div>
                                <h1 class="text-base font-bold text-slate-900 leading-tight flex items-center gap-2">
                                    Hourly Reporting System
                                </h1>
                                <p class="text-[11px] text-slate-500 font-medium">Multi-Platform Central Automation</p>
                            </div>
                        </Link>

                        <!-- Live PHT Clock Chip -->
                        <div class="hidden xl:flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-slate-100 text-slate-700 border border-slate-200">
                            <span class="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
                            <span class="font-mono">{{ phtTime }} PHT</span>
                        </div>
                    </div>

                    <!-- Navigation Links (Desktop) -->
                    <nav class="hidden md:flex items-center space-x-1">
                        <Link
                            v-for="item in navItems"
                            :key="item.name"
                            :href="item.href"
                            class="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg text-sm font-medium transition duration-150"
                            :class="[
                                item.current(page.url)
                                    ? (item.highlight ? 'bg-rose-50 text-rose-700 font-semibold shadow-2xs border border-rose-200' : 'bg-indigo-50 text-indigo-700 font-semibold shadow-2xs border border-indigo-100')
                                    : 'text-slate-600 hover:text-slate-900 hover:bg-slate-100'
                            ]"
                        >
                            <component :is="item.icon" class="w-4 h-4" :class="item.highlight ? 'text-rose-600' : ''" :stroke-width="1.75" />
                            <span>{{ item.name }}</span>
                            <span v-if="item.highlight" class="ml-0.5 px-1.5 py-0.2 bg-rose-500 text-white rounded text-[10px] font-black uppercase tracking-wider">
                                New
                            </span>
                        </Link>
                    </nav>

                    <!-- Right Actions -->
                    <div class="flex items-center gap-3">
                        <button
                            type="button"
                            @click="triggerReportGeneration"
                            :disabled="isGenerating"
                            class="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-semibold text-white bg-indigo-600 hover:bg-indigo-700 active:bg-indigo-800 disabled:opacity-50 transition shadow-xs shadow-indigo-600/20 hover:shadow-sm cursor-pointer min-h-[40px]"
                            title="Trigger an automated report snapshot immediately"
                        >
                            <Loader2 v-if="isGenerating" class="w-4 h-4 animate-spin" :stroke-width="2" />
                            <Play v-else class="w-3.5 h-3.5 fill-current" :stroke-width="2" />
                            <span>{{ isGenerating ? 'Generating...' : 'Generate Report Now' }}</span>
                        </button>
                    </div>
                </div>
            </div>
        </header>

        <!-- Flash Messages (Inertia Props) -->
        <div v-if="$page.props.flash?.success || $page.props.flash?.error" class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-4 w-full">
            <div
                v-if="$page.props.flash?.success"
                class="rounded-xl p-3.5 bg-emerald-50 border border-emerald-200/80 text-emerald-800 text-sm flex items-center justify-between shadow-xs"
            >
                <div class="flex items-center gap-2.5">
                    <CheckCircle2 class="w-5 h-5 text-emerald-600 shrink-0" :stroke-width="2" />
                    <span>{{ $page.props.flash.success }}</span>
                </div>
            </div>

            <div
                v-if="$page.props.flash?.error"
                class="rounded-xl p-3.5 bg-rose-50 border border-rose-200/80 text-rose-800 text-sm flex items-center justify-between shadow-xs"
            >
                <div class="flex items-center gap-2.5">
                    <AlertCircle class="w-5 h-5 text-rose-600 shrink-0" :stroke-width="2" />
                    <span>{{ $page.props.flash.error }}</span>
                </div>
            </div>
        </div>

        <!-- Main Content Slot -->
        <main class="flex-1 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 w-full">
            <slot />
        </main>

        <!-- Mobile Bottom Thumb-Zone Navigation Bar -->
        <div class="md:hidden fixed bottom-0 left-0 right-0 z-40 bg-white/95 backdrop-blur-md border-t border-slate-200 px-2 py-1 shadow-lg flex items-center justify-around">
            <Link
                v-for="item in navItems"
                :key="item.name"
                :href="item.href"
                class="flex flex-col items-center justify-center py-1.5 px-2 rounded-lg text-[10px] font-medium min-h-[44px] min-w-[56px] transition-colors"
                :class="[
                    item.current(page.url)
                        ? 'text-indigo-600 font-semibold bg-indigo-50/70'
                        : 'text-slate-500 hover:text-slate-900'
                ]"
            >
                <component :is="item.icon" class="w-5 h-5 mb-0.5" :stroke-width="1.75" />
                <span>{{ item.name }}</span>
            </Link>
        </div>

        <!-- Desktop Footer -->
        <footer class="bg-white border-t border-slate-200/80 mt-auto py-6">
            <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col md:flex-row items-center justify-between gap-4 text-xs text-slate-500">
                <div class="flex items-center gap-2">
                    <span class="font-semibold text-slate-700">Hourly Reporting Automation System</span>
                    <span>•</span>
                    <span class="text-amber-600 font-medium">Prototype MVP</span>
                    <span>•</span>
                    <span class="text-slate-400 font-mono">{{ phtTime }} PHT</span>
                </div>
                <div>
                    Built with Laravel 12 + Vue 3 + Inertia.js + Tailwind CSS. Multi-platform API expandable architecture.
                </div>
            </div>
        </footer>
    </div>
</template>

// autoreportFront/src/layouts/AppLayout.tsx
import React, { useState, useEffect } from 'react';
import {
  Box,
  Drawer,
  AppBar,
  Toolbar,
  Typography,
  IconButton,
  List,
  ListItem,
  ListItemButton,
  ListItemIcon,
  ListItemText,
  Button,
  Chip,
  Container,
  Divider,
  useMediaQuery,
  useTheme,
  Snackbar,
  Alert,
  CircularProgress,
  Tooltip,
} from '@mui/material';
import {
  DashboardRounded,
  ShoppingBagRounded,
  TrendingUpRounded,
  AssessmentRounded,
  StoreRounded,
  LayersRounded,
  MemoryRounded,
  PlayArrowRounded,
  MenuRounded,
  Brightness4Rounded,
  Brightness7Rounded,
  AccessTimeRounded,
  AutoAwesomeRounded,
} from '@mui/icons-material';
import { Link, useLocation } from 'react-router-dom';
import { ReportsService } from '../services/api';

const DRAWER_WIDTH = 260;

interface AppLayoutProps {
  children: React.ReactNode;
  mode: 'light' | 'dark';
  onToggleTheme: () => void;
}

export const AppLayout: React.FC<AppLayoutProps> = ({ children, mode, onToggleTheme }) => {
  const theme = useTheme();
  const location = useLocation();
  const isMobile = useMediaQuery(theme.breakpoints.down('md'));
  const [mobileOpen, setMobileOpen] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [phtTime, setPhtTime] = useState('');
  const [toast, setToast] = useState<{ open: boolean; message: string; severity: 'success' | 'error' }>({
    open: false,
    message: '',
    severity: 'success',
  });

  // Clock in Asia/Manila (PHT)
  useEffect(() => {
    const updateTime = () => {
      try {
        const formatted = new Intl.DateTimeFormat('en-US', {
          timeZone: 'Asia/Manila',
          hour: 'numeric',
          minute: '2-digit',
          second: '2-digit',
          hour12: true,
        }).format(new Date());
        setPhtTime(formatted);
      } catch {
        setPhtTime('PHT');
      }
    };
    updateTime();
    const interval = setInterval(updateTime, 1000);
    return () => clearInterval(interval);
  }, []);

  const handleDrawerToggle = () => {
    setMobileOpen(!mobileOpen);
  };

  const triggerGlobalReport = async () => {
    if (isGenerating) return;
    setIsGenerating(true);
    try {
      const res = await ReportsService.generateReport();
      setToast({
        open: true,
        message: res.message || 'Hourly report snapshot generated successfully!',
        severity: 'success',
      });
    } catch (err: any) {
      setToast({
        open: true,
        message: err?.response?.data?.message || 'Failed to trigger report generation.',
        severity: 'error',
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const navItems = [
    { label: 'Dashboard', path: '/', icon: <DashboardRounded /> },
    {
      label: 'Shopee Breakdown',
      path: '/shopee',
      icon: <ShoppingBagRounded sx={{ color: '#EE4D2D' }} />,
      badge: 'Shopee',
      badgeColor: '#EE4D2D',
    },
    {
      label: 'TikTok Breakdown',
      path: '/tiktok',
      icon: <TrendingUpRounded sx={{ color: '#E11D48' }} />,
      badge: 'TikTok',
      badgeColor: '#E11D48',
    },
    { label: 'Reports', path: '/reports', icon: <AssessmentRounded /> },
    { label: 'Shops', path: '/shops', icon: <StoreRounded /> },
    { label: 'Platforms', path: '/platforms', icon: <LayersRounded /> },
    { label: 'Automation', path: '/automation', icon: <MemoryRounded /> },
  ];

  const drawerContent = (
    <Box sx={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
      {/* Brand Header */}
      <Box sx={{ p: 2.5, display: 'flex', alignItems: 'center', gap: 1.5 }}>
        <Box
          sx={{
            width: 40,
            height: 40,
            borderRadius: 3,
            bgcolor: 'primary.main',
            color: '#fff',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            fontWeight: 900,
            fontSize: 18,
            boxShadow: '0 4px 12px rgba(79, 70, 229, 0.3)',
          }}
        >
          K
        </Box>
        <Box>
          <Typography variant="subtitle1" sx={{ fontWeight: 800, lineHeight: 1.2 }}>
            Hourly Reporting
          </Typography>
          <Typography variant="caption" sx={{ color: 'text.secondary', fontWeight: 500 }}>
            React 19 + Laravel API
          </Typography>
        </Box>
      </Box>

      <Divider sx={{ mx: 2 }} />

      {/* Nav List */}
      <List sx={{ px: 1.5, py: 2, flexGrow: 1 }}>
        {navItems.map((item) => {
          const isActive =
            item.path === '/'
              ? location.pathname === '/'
              : location.pathname.startsWith(item.path);

          return (
            <ListItem key={item.label} disablePadding sx={{ mb: 0.75 }}>
              <ListItemButton
                component={Link}
                to={item.path}
                onClick={() => isMobile && setMobileOpen(false)}
                sx={{
                  borderRadius: 2.5,
                  py: 1.2,
                  px: 2,
                  bgcolor: isActive
                    ? item.badgeColor
                      ? `${item.badgeColor}15`
                      : 'primary.main'
                    : 'transparent',
                  color: isActive
                    ? item.badgeColor
                      ? item.badgeColor
                      : '#FFFFFF'
                    : 'text.primary',
                  border: isActive && item.badgeColor ? `1px solid ${item.badgeColor}40` : 'none',
                  '&:hover': {
                    bgcolor: isActive
                      ? item.badgeColor
                        ? `${item.badgeColor}25`
                        : 'primary.dark'
                      : 'action.hover',
                  },
                }}
              >
                <ListItemIcon
                  sx={{
                    minWidth: 38,
                    color: isActive
                      ? item.badgeColor
                        ? item.badgeColor
                        : '#FFFFFF'
                      : 'text.secondary',
                  }}
                >
                  {item.icon}
                </ListItemIcon>
                <ListItemText
                  primary={item.label}
                  primaryTypographyProps={{
                    fontSize: '0.875rem',
                    fontWeight: isActive ? 700 : 500,
                  }}
                />
                {item.badge && (
                  <Chip
                    label={item.badge}
                    size="small"
                    sx={{
                      height: 20,
                      fontSize: '0.65rem',
                      fontWeight: 800,
                      bgcolor: item.badgeColor,
                      color: '#fff',
                    }}
                  />
                )}
              </ListItemButton>
            </ListItem>
          );
        })}
      </List>

      {/* Drawer Footer Status */}
      <Box sx={{ p: 2, m: 1.5, borderRadius: 3, bgcolor: mode === 'dark' ? 'rgba(255,255,255,0.03)' : '#F1F5F9' }}>
        <Typography variant="caption" sx={{ fontWeight: 700, color: 'text.secondary', display: 'block' }}>
          CONNECTED MARKETPLACES
        </Typography>
        <Box sx={{ display: 'flex', gap: 1, mt: 1 }}>
          <Chip label="Shopee" size="small" sx={{ bgcolor: '#EE4D2D', color: '#fff', fontSize: '0.7rem', fontWeight: 700 }} />
          <Chip label="TikTok" size="small" sx={{ bgcolor: '#E11D48', color: '#fff', fontSize: '0.7rem', fontWeight: 700 }} />
        </Box>
      </Box>
    </Box>
  );

  return (
    <Box sx={{ display: 'flex', minHeight: '100vh', bgcolor: 'background.default' }}>
      {/* Prototype Banner */}
      <Box
        sx={{
          position: 'fixed',
          top: 0,
          left: 0,
          right: 0,
          zIndex: (theme) => theme.zIndex.drawer + 2,
          bgcolor: mode === 'dark' ? '#3B2D08' : '#FEF3C7',
          color: mode === 'dark' ? '#FDE68A' : '#92400E',
          borderBottom: '1px solid',
          borderColor: mode === 'dark' ? '#78350F' : '#FCD34D',
          px: 2,
          py: 0.5,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          fontSize: '0.75rem',
        }}
      >
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          <Chip
            icon={<AutoAwesomeRounded sx={{ fontSize: '14px !important', color: 'inherit !important' }} />}
            label="PROTOTYPE"
            size="small"
            sx={{ height: 20, fontSize: '0.65rem', fontWeight: 900, bgcolor: '#F59E0B', color: '#000' }}
          />
          <Typography variant="caption" sx={{ fontWeight: 600 }}>
            React 19 Frontend + Laravel REST API — Independent Shopee & TikTok Multi-Channel Reporting
          </Typography>
        </Box>
        <Box sx={{ display: { xs: 'none', sm: 'flex' }, alignItems: 'center', gap: 0.5 }}>
          <AccessTimeRounded sx={{ fontSize: 14 }} />
          <Typography variant="caption" sx={{ fontWeight: 600 }}>
            Philippine Standard Time (PHT, UTC+8)
          </Typography>
        </Box>
      </Box>

      {/* Top App Bar */}
      <AppBar
        position="fixed"
        sx={{
          top: 29, // height of prototype banner
          width: { md: `calc(100% - ${DRAWER_WIDTH}px)` },
          ml: { md: `${DRAWER_WIDTH}px` },
          bgcolor: mode === 'dark' ? 'rgba(17, 24, 39, 0.8)' : 'rgba(255, 255, 255, 0.85)',
          backdropFilter: 'blur(12px)',
          borderBottom: '1px solid',
          borderColor: 'divider',
          color: 'text.primary',
          boxShadow: 'none',
          zIndex: (theme) => theme.zIndex.drawer + 1,
        }}
      >
        <Toolbar sx={{ justifyContent: 'space-between' }}>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
            <IconButton
              color="inherit"
              edge="start"
              onClick={handleDrawerToggle}
              sx={{ mr: 1, display: { md: 'none' } }}
            >
              <MenuRounded />
            </IconButton>

            {/* Live Clock Chip */}
            <Chip
              icon={
                <Box
                  sx={{
                    width: 8,
                    height: 8,
                    borderRadius: '50%',
                    bgcolor: '#10B981',
                    ml: 1,
                    animation: 'pulse 2s infinite',
                  }}
                />
              }
              label={`${phtTime || 'Loading...'} PHT`}
              size="small"
              sx={{
                fontWeight: 700,
                fontFamily: 'monospace',
                fontSize: '0.75rem',
                bgcolor: mode === 'dark' ? 'rgba(255,255,255,0.05)' : '#F1F5F9',
                color: 'text.primary',
                border: '1px solid',
                borderColor: 'divider',
              }}
            />
          </Box>

          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
            {/* Theme Toggle */}
            <Tooltip title={`Switch to ${mode === 'light' ? 'Dark' : 'Light'} Mode`}>
              <IconButton onClick={onToggleTheme} color="inherit" size="small">
                {mode === 'dark' ? <Brightness7Rounded /> : <Brightness4Rounded />}
              </IconButton>
            </Tooltip>

            {/* Quick Action Generate */}
            <Button
              variant="contained"
              color="primary"
              size="small"
              onClick={triggerGlobalReport}
              disabled={isGenerating}
              startIcon={isGenerating ? <CircularProgress size={16} color="inherit" /> : <PlayArrowRounded />}
              sx={{ fontSize: '0.8125rem' }}
            >
              {isGenerating ? 'Generating...' : 'Generate Snapshot'}
            </Button>
          </Box>
        </Toolbar>
      </AppBar>

      {/* Navigation Drawer */}
      <Box component="nav" sx={{ width: { md: DRAWER_WIDTH }, flexShrink: { md: 0 } }}>
        {/* Mobile Drawer */}
        <Drawer
          variant="temporary"
          open={mobileOpen}
          onClose={handleDrawerToggle}
          ModalProps={{ keepMounted: true }}
          sx={{
            display: { xs: 'block', md: 'none' },
            '& .MuiDrawer-paper': {
              boxSizing: 'border-box',
              width: DRAWER_WIDTH,
              top: 29,
              height: 'calc(100% - 29px)',
            },
          }}
        >
          {drawerContent}
        </Drawer>

        {/* Desktop Permanent Drawer */}
        <Drawer
          variant="permanent"
          sx={{
            display: { xs: 'none', md: 'block' },
            '& .MuiDrawer-paper': {
              boxSizing: 'border-box',
              width: DRAWER_WIDTH,
              top: 29,
              height: 'calc(100% - 29px)',
              borderRight: '1px solid',
              borderColor: 'divider',
            },
          }}
          open
        >
          {drawerContent}
        </Drawer>
      </Box>

      {/* Main Content Area */}
      <Box
        component="main"
        sx={{
          flexGrow: 1,
          p: { xs: 2, sm: 3, md: 4 },
          width: { md: `calc(100% - ${DRAWER_WIDTH}px)` },
          mt: '93px', // 29px (notice) + 64px (appbar)
          minHeight: 'calc(100vh - 93px)',
          display: 'flex',
          flexDirection: 'column',
        }}
      >
        <Container maxWidth="xl" sx={{ flexGrow: 1, p: '0 !important' }}>
          {children}
        </Container>

        {/* Footer */}
        <Box
          component="footer"
          sx={{
            mt: 6,
            pt: 3,
            borderTop: '1px solid',
            borderColor: 'divider',
            display: 'flex',
            flexDirection: { xs: 'column', sm: 'row' },
            justifyContent: 'space-between',
            alignItems: 'center',
            gap: 2,
            color: 'text.secondary',
            fontSize: '0.75rem',
          }}
        >
          <Typography variant="caption">
            <strong>KCG Automated Reporting System</strong> • React 19 + Material UI v6 • {phtTime} PHT
          </Typography>
          <Typography variant="caption">
            Connected to Laravel API via Axios • Independent Shopee & TikTok Automation
          </Typography>
        </Box>
      </Box>

      {/* Global Alert Notification Toast */}
      <Snackbar
        open={toast.open}
        autoHideDuration={5000}
        onClose={() => setToast({ ...toast, open: false })}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'right' }}
      >
        <Alert
          onClose={() => setToast({ ...toast, open: false })}
          severity={toast.severity}
          variant="filled"
          sx={{ width: '100%', borderRadius: 2 }}
        >
          {toast.message}
        </Alert>
      </Snackbar>
    </Box>
  );
};
